### ISSUE TITLE
encoder linearization about lut_offset value

### ISSUE THREAD

**Issue by Apex-yuan** [bgkatz/motorcontrol#14]
I am a brushless motor hobbyist and am happy to see this open source project. I have a question about encoder linearization:
in calibration.c file
`int lut_offset = (ENC_CPR-cal->error_arr[0])*N_LUT/ENC_CPR`
I think the lut_offset should be `cal->error_arr[0]*N_LUT/ENC_CPR`. What did I do wrong

**Comment by wwwwwwzj** [comment]
我觉得也不用加ENC_CPR。你有对比过加与不加的校准效果吗？
