### ISSUE TITLE
the new version stuck when setting zero position

### ISSUE THREAD

**Issue by chongxi** [bgkatz/motorcontrol#6]
The update of the firmware 2.0 looks nice. Thanks, @bgkatz, so far I have entered one problem consistently. 

This issue is triggered when the code runs into the function of `HAL_Delay(20)` in the step of `update_fsm`, which is in the `fsm.c` file. It just stuck there and never goes to the next step. 

Since `update_fsm` is reused in both the `CAN1_RX0_IRQHandler` and `USART2_IRQHandler`, set zero position makes the firmware stuck either from serial configuration or from CAN communication. 

Here is part of the code in `update_fsm`: 
```c
	switch(fsmstate->state){
		case MENU_MODE:
			switch (fsm_input){
				case CAL_CMD:
					fsmstate->next_state = CALIBRATION_MODE;
					fsmstate->ready = 0;
					break;
				case MOTOR_CMD:
					fsmstate->next_state = MOTOR_MODE;
					fsmstate->ready = 0;
					break;
				case ENCODER_CMD:
					fsmstate->next_state = ENCODER_MODE;
					fsmstate->ready = 0;
					break;
				case SETUP_CMD:
					fsmstate->next_state = SETUP_MODE;
					fsmstate->ready = 0;
					break;
				case ZERO_CMD:
					printf("\n\r Try setting new zero position. \n\r");
					comm_encoder.m_zero = 0;
					ps_sample(&comm_encoder, DT);
					HAL_Delay(20);
					M_ZERO = comm_encoder.count;
					//if (!prefs.ready()) prefs.open();
					//    prefs.flush();                                                  // Write new prefs to flash
					//    prefs.close();
					//    prefs.load();
					//spi.SetMechOffset(M_OFFSET);
//					printf("\n\r Saved new zero position\n\r\n\r");
//					printf(M_ZERO);
					printf("\n\r  Saved new zero position:  %d\n\r\n\r", M_ZERO);
					break;
				}
```

I appreciate it if any solution is suggested @bgkatz. Thanks!

**Comment by chongxi** [comment]
I think this is a ISR priority issue:

```c
  HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);  // here I change NVIC_PRIORITYGROUP_0 to NVIC_PRIORITYGROUP_4
```

**Comment by chongxi** [comment]
As pointed out [here](https://stackoverflow.com/questions/53899882/hal-delay-stuck-in-a-infinite-loop): 
> All delay and timeout HAL functions rely on a counter incremented in the `SysTick` handler. If you are using any of these functions in another interrupt, you have to make sure that the `SysTick` interrupt has a higher priority than that interrupt. Otherwise, the `SysTick` handler is never called and you will end up in an infinite loop, as the counter will never be increased.

[Other people have reported the same issue when both the UART ISR and SysTick shared the same priority](https://community.st.com/s/question/0D50X0000C22U7gSQE/haldelay-never-exits-even-after-increasing-the-priority-of-systick-to-highest-priority)


If you use @bgkatz code here with your own library setting and you have this issue: 
> Possibilities: 
> 1) SysTick interrupt isn't set up or enabled. 
> 2) interrupts are disabled. 
> 3) priority of SysTick is less or equal to that of the UART/CAN. Note that a priority of 0 is the highest priority. 
> 4) interrupts cannot preempt each other. Check priority grouping setting (`HAL_NVIC_SetPriorityGrouping` cannot use `NVIC_PRIORITYGROUP_4`).

**Comment by bgkatz** [comment]
The issue here was simply that I had not implemented saving the zero position.  Should work now.
