### ISSUE TITLE
What is the principle of smv function and how does it work

### ISSUE THREAD

**Issue by yulinwuya** [bgkatz/motorcontrol#7]
Why can smv() calculate the duty cycle of SVPWM? I can't understand the working principle of this function. Do you have any reference materials to share?

The function is located in   >>   motorcontrol/Core/Src/foc.c

`void svm(float v_max, float u, float v, float w, float *dtc_u, float *dtc_v, float *dtc_w){
    /* Space Vector Modulation
     u,v,w amplitude = v_bus for full modulation depth */

    float v_offset = (fminf3(u, v, w) + fmaxf3(u, v, w))*0.5f;
    float v_midpoint = .5f*(DTC_MAX+DTC_MIN);

    *dtc_u = fast_fminf(fast_fmaxf((.5f*(u -v_offset)*OVERMODULATION/v_max + v_midpoint ), DTC_MIN), DTC_MAX);
    *dtc_v = fast_fminf(fast_fmaxf((.5f*(v -v_offset)*OVERMODULATION/v_max + v_midpoint ), DTC_MIN), DTC_MAX);
    *dtc_w = fast_fminf(fast_fmaxf((.5f*(w -v_offset)*OVERMODULATION/v_max + v_midpoint ), DTC_MIN), DTC_MAX);

    }`

**Comment by bgkatz** [comment]
This is the simplest implementation of SVM.  
This Microchip guide has good explanations of different SVM techniques, including this one:
https://microchipdeveloper.com/mct5001:start
https://microchipdeveloper.com/mct5001:which-zsm-is-best

**Comment by yulinwuya** [comment]
I see. Thank you very much！！
